FROM tiangolo/uvicorn-gunicorn:latest

# Establece el directorio de trabajo en el contenedor
WORKDIR /back-end

ENV PYTHONUNBUFFERED 1 
ENV PYTHONPATH "${PYTHONPATH}:/app"


COPY ./requirements.txt .   

RUN pip install --no-cache-dir -r requirements.txt

COPY . /back-end/

CMD uvicorn --host 0.0.0.0 --port 8220 main:app



